Carlos Created GraphingData class
Breaking-Bias/CashApp_FTL pull request #116
Opened 2024-11-16 20:43 UTC by solarescarlos

Created a new GraphingData class in graphing_data.py to make our code usable, nice, and pretty, and to pass around the same data object consistently in the backend. 

This class stores a data frame with two columns. Column 1 must be labelled "date" and column 2 must be labelled either "frequency" or "revenue".

Cheers

2024-11-16 21:09 UTC, MatthewFrieri approved these changes

2024-11-16 21:28 UTC, Adventurer-E commented on backend/graphing_data.py
> +        self.data = pd.DataFrame
?

2024-11-16 21:33 UTC, Adventurer-E commented
Do you guys think it's a good idea to make GraphingData a child class of pd.DataFrame? In this way, we would directly uswe the GraphingData variables as DataFrames without having to call getData().

2024-11-16 21:40 UTC, solarescarlos commented on backend/graphing_data.py
> +        self.data = pd.DataFrame
Yup, just caught that. Changing now.

2024-11-16 21:42 UTC, solarescarlos commented on backend/graphing_data.py
> +class GraphingData:
I assume this is for readability. I'll add it in

2024-11-16 21:45 UTC, solarescarlos commented
> Do you guys think it's a good idea to make GraphingData a child class of pd.DataFrame? In this way, we would directly uswe the GraphingData variables as DataFrames without having to call getData().

That would be kinda cool for later, I think right now though we should focus on getting this working with the other refactorings.

2024-11-17 04:13 UTC, BardyBard requested changes
Also can you make some simple tests, showing that it works on a properly formatted df and fails on a bad df

2024-11-17 04:13 UTC, BardyBard commented on backend/graphing_data.py
> +        assert data.columns[0] == "data", "First column header must be 'data'."
make sure that is a datetime.date object, and column name should be "date" not data

2024-11-17 04:15 UTC, BardyBard commented
> Do you guys think it's a good idea to make GraphingData a child class of pd.DataFrame? In this way, we would directly uswe the GraphingData variables as DataFrames without having to call getData().

I did not know this was a possibility, that could be a very cool implementation if you can figure out how to do that, I think Paul would be very excited. However, if its complicated for some reason it's not a priority.

2024-11-17 17:38 UTC, Adventurer-E commented
> > Do you guys think it's a good idea to make GraphingData a child class of pd.DataFrame? In this way, we would directly uswe the GraphingData variables as DataFrames without having to call getData().
> 
> @Adventurer-E @solarescarlos
> 
> I did not know this was a possibility, that could be a very cool implementation if you can figure out how to do that, I think Paul would be very excited. However, if its complicated for some reason it's not a priority.

Never mind. For now I've implemented ModelInteractor as if GraphingData is not a child of DataFrame.

2024-11-17 18:03 UTC, Adventurer-E requested changes
Could you also create a new method GraphingData1.equals(GraphingData2) that checks whether the two contents in GraphingData are equal? It is needed for pytests in other modules. Currently, since GraphingData are objects, a simple == only do address check, which is not what we want.

2024-11-17 18:48 UTC, Adventurer-E requested changes

2024-11-17 18:48 UTC, Adventurer-E commented on backend/graphing_data.py
> +        return self.data
`.copy()`
self.data shouldn't be mutable when it's called.

2024-11-18 22:10 UTC, Adventurer-E commented
Icannot see flake8 changes under File Changed 🙁

2024-11-18 22:11 UTC, solarescarlos commented
> Icannot see flake8 changes under File Changed 🙁

You can't see my style changes?

2024-11-18 22:27 UTC, avantitandon reviewed
can't see the flake changes either Carlos

2024-11-18 22:30 UTC, solarescarlos commented
> can't see the flake changes either Carlos

You can't see this?
![Screenshot (119)](https://github.com/user-attachments/assets/22277c92-5b36-4426-9879-e610a8e0ce69)

2024-11-18 22:32 UTC, avantitandon approved these changes

2024-11-18 22:42 UTC, merged